net: skbuff - Remove Legacy SFE fast_forwarded definition change to avoid compilation conflict
ERROR
skbuff.h:1024:9: error: duplicate member 'fast_forwarded'
[1024] __u8 fast_forwarded:1;
skbuff.h:990:9: note: previous declaration is here
[990] __u8 fast_forwarded:1;

The fast_forwarded field is already defined outside of
the CONFIG_ENABLE_SFE block (line 1020). Removing the
redundant definition within the CONFIG_ENABLE_SFE
block to avoid compilation issue.

Change-Id: I09131fa888114b6b910d3935f86d684ed73b0064
Signed-off-by: Medha <quic_medhlnu@quicinc.com>