power: supply: Add qcom folder for charger/qg drivers
Add the qcom folder and snapshots of qpnp-smb5, qpnp-qg,
smb1355-charger, smb1398-charger drivers and their dependencies.

The snapshots of smb1355-charger.c and smb1398-charger.c are taken
from qcom-6.1 kernel branch and the snapshots of all other files
are taken from qcom-6.6 kernel branch 'commit d19c4c687d76 ("soc:
qcom: minidump: Fix race in log_cpu_freq")'.

Also
- Replace the QuIC copyright with the QTI copyright for the files
- Update the remove callbacks to have void return values to fix
the compilation error: "error: incompatible function pointer types
initializing 'void (*)(struct platform_device *)' with an
expression of type 'int (struct platform_device *)'" on 6.12 kernel.

Change-Id: I50a74aed0eb2c867741612bc14f1d14cff980de6
Signed-off-by: Shilpa Suresh <c_sbsure@qti.qualcomm.com>