power: supply: Add smblite, qbg drivers and their dependencies
Add snapshots of qpnp-smblite, qti-qbg driver files and their
dependencies.

The snapshots are taken from qcom-6.6 kernel commit 22ac8efdd0b1
("modules.list.msm.kera-le: Add nvmem_qfprom to first stage on kera").

Also
- Replace the QuIC copyright with the QTI copyright for the files.
- Make changes to support the new modifications in power_supply_desc
  structure on 6.12 kernel.
- Update the remove callbacks to have void return values to fix
  the compilation error: "error: incompatible function pointer types
  initializing 'void (*)(struct platform_device *)' with an
  expression of type 'int (struct platform_device *)'" on 6.12 kernel.

Change-Id: I886f93662e86abdb3b27dd07c3666683ca4b890d
Signed-off-by: Shilpa Suresh <c_sbsure@qti.qualcomm.com>