soc: qcom: Add snapshot for AON event bridge driver
Add snapshot of AON event bridge and respective rpmsg drivers
along with their dependencies from qcom-6.6.

Snapshot is taken from qcom-6.6 kernel commit 22ac8efdd0b1
("modules.list.msm.kera-le: Add nvmem_qfprom to first stage on kera").

Also
- Replace the QuIC copyright with the QTI copyright for the files
- Update the remove callback to have void return value to fix
the compilation error: "error: incompatible function pointer types
initializing 'void (*)(struct platform_device *)' with an
expression of type 'int (struct platform_device *)'" on 6.12 kernel.

Change-Id: Ib4a58cad82a86466a9d713a2566b5e06b72ddd7a
Signed-off-by: Koushik Immadisetty <quic_kimmadis@quicinc.com>
Signed-off-by: Shilpa Suresh <c_sbsure@qti.qualcomm.com>